Fixed #195 issue
pyhoneybot/honeybot pull request #202
Opened 2024-09-04 11:49 UTC by OussamaERrafif

Fixed #195 issue

2024-09-04 19:48 UTC, MrTanoshii requested changes
Hi @OussamaERrafif ,

Thank you for your first PR, please have a look at the requested changes and let me know if you need any help

2024-09-04 19:53 UTC, MrTanoshii requested changes

2024-09-04 19:53 UTC, MrTanoshii commented on src/honeybot/api/main.py
> +        self.core_plugins = []
`class BotCore` and its `__init__()` are duplicated 3 times, please remove the duplicates

First duplicate

2024-09-04 19:53 UTC, MrTanoshii commented on src/honeybot/api/main.py
> +        self.core_plugins = []
Second duplicate

2024-09-04 19:53 UTC, MrTanoshii commented on src/honeybot/api/main.py
>  class BotCore:
Start of third duplicate until L208

2024-09-04 19:53 UTC, MrTanoshii commented on src/honeybot/api/main.py
> +                    pass
Too much indentation?

2024-09-05 15:01 UTC, OussamaERrafif commented
@MrTanoshii Thanks for noticing these errors

2024-09-06 11:21 UTC, MrTanoshii approved these changes

2024-09-06 11:22 UTC, merged

2024-09-06 11:22 UTC, MrTanoshii commented
Thanks for the PR @OussamaERrafif